### ISSUE TITLE
Hackday: How to Teach MATLAB Tutorial - Jan 18

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/2i2cAccessPolicies#6]
Copied from https://github.com/NASA-Openscapes/2i2cAccessPolicies/discussions/5 as we test project boards and calendaring with GitHub Issues

Hi All -

We are going to get together for another round of the NASA Earthdata in the Cloud MATLAB tutorials using [2i2c JupyterHub](https://openscapes.2i2c.cloud/) next Thursday, Jan 18 from 3-5pm ET. I'm happy to send a calendar invite if you want to attend.
This tutorial will cover:

    https://nasa-openscapes.github.io/earthdata-cloud-cookbook/tutorials/matlab.html

    The how-do I read data has some additional matlab info: https://nasa-openscapes.github.io/earthdata-cloud-cookbook/how-tos/read_data.html

    You will need a [Github account](https://github.com/), an [Earthdata login](https://urs.earthdata.nasa.gov/)

The material, if it goes well, will be recorded and shared back and posted in the cookbook. If you can't make this time and would like to schedule a quick session, I'm happy to coordinate that with you after the 18th.

Happy New Year and thanks for your interest in trying this approach out -

**Comment by stefaniebutland** [comment]
I will add MATLAB video to youtube & link in Cookbook

**Comment by jules32** [comment]
Excellent! closing
